version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'range-connect_rabbitmq'
    container_name: 'range-connect_rabbitmq'
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rangeconnect
      - RABBITMQ_DEFAULT_PASS=Uivq9ACXS49W
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - range-connect

networks:
  range-connect:
    driver: bridge